apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poinz-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: poinz.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: poinz-server-service
                port:
                  number: 3000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: poinz-server-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: poinz-client-service
                port:
                  number: 9000
